echo -e "`clear` $(tput sgr0) \n -- \n HOSTNAME: `hostname` \n --- \n Status: \n";
cat /proc/loadavg|awk '{print $1}'|while read output; do echo -e "Load average: $output"; 
usep2=$(echo $output|cut -d\. -f1); 
if [ $usep2 -ge 10 ]; then echo "$(tput sgr0)Running $(tput setaf 1)on HIGH LOAD $output $(tput sgr0)on $(hostname) as on $(date) $(tput sgr0)"; fi;done;
echo -e "\nMemory:";free -m;echo -e "\n---\nService Status: \n"; 
pgrep httpd  > /dev/null && echo "$(tput sgr0)apache $(tput setaf 2)up$(tput sgr0)" || echo "$(tput sgr0)Apache $(tput setaf 1)DOWN";
pgrep named > /dev/null && echo "$(tput sgr0)named $(tput setaf 2)up$(tput sgr0)" || echo "named $(tput setaf 1)DOWN$(tput sgr0)";
pgrep mysql* > /dev/null && echo "$(tput sgr0)mysql $(tput setaf 2)up$(tput sgr0)" || echo "mysql $(tput setaf 1)DOWN$(tput sgr0)";

if [ -f /etc/init.d/cpanel ]; 
then pgrep cpsrvd >> /dev/null && echo "$(tput sgr0)cpanel $(tput setaf 2)up$(tput sgr0)" || echo "$(tput sgr0)cpanel $(tput setaf 1)DOWN$(tput sgr0)";pgrep exim > /dev/null && echo "$(tput sgr0)exim $(tput setaf 2)up$(tput sgr0)" || echo "exim $(tput setaf 1)DOWN$(tput sgr0)"; else if [ -f /etc/init.d/psa ]; then pgrep qmail > /dev/null && echo "$(tput sgr0)qmail $(tput setaf 2)up$(tput sgr0)" || echo "qmail $(tput setaf 1)DOWN$(tput sgr0)";pgrep sw-cp-serverd > /dev/null && echo "$(tput sgr0)Plesk $(tput setaf 2)up$(tput sgr0)" || echo "Plesk $(tput setaf 1)DOWN$(tput sgr0)"; else  echo "no control panel"; fi; fi;echo -e "$(tput sgr0) \n --- \n DISK USAGE: \n";df -H | grep -vE '^Filesystem|tmpfs|cdrom|simfs|none' | awk '{ print $5 " " $1 }' | while read output; do echo $output; usep=$(echo $output | awk '{ print $1}' | cut -d'%' -f1 ); partition=$(echo $output | awk '{ print $2 }' ); if [ $usep -ge 90 ]; then echo "$(tput sgr0)Running $(tput setaf 1)out of space \"$partition ($usep%)\" $(tput sgr0)on $(hostname) as on $(date) $(tput sgr0)"; fi;done;echo -e "\n";while true; do read -p "Need detailed disk usage?" yn; case $yn in [Yy]* ) echo -ne " \n --- \n DETAILED DISK USAGE: \n\n"; echo -ne "\r\n\n`cd /;du 2> /dev/null -ch * --max-depth=10|grep G|grep -v M|grep -v K|xargs -L 5 |xargs -I@ echo -n "= ";sleep 1;` \n `du 2> /dev/null -ch * --max-depth=10|grep G|grep -v M|grep -v K|grep -v virtfs|more` \n" > diskusage.txt;cat diskusage.txt |more; break;; [Nn]* ) break;; * ) echo "Please answer yes or no.";; esac; done; while true; do     read -p "Do you wish to view processes?" yn; case $yn in [Yy]* ) echo -e "Processes: \n `pstree 2> /dev/null -A || pstree 2> /dev/null -a |more`"; break;; [Nn]* ) break;; * ) echo "Please answer yes or no.";; esac; done; while true; do read -p "Want to create client report?" yn; case $yn in [Yy]* ) echo -e "Client Report : `hostname;w;pstree 2> /dev/null -A || pstree 2> /dev/null -a ;` \n\nDisk Usage: \n ` df -H | grep -vE '^Filesystem|tmpfs|cdrom|simfs|none'`"; break;; [Nn]* ) break;; * ) echo "Please answer yes or no.";; esac; done;echo -e "checking mail queue...\n current count of mails on queue: `exim -bpc`";mailq=$(exim -bpc);if [ mailq ge 50]; then echo "suspected spamming"; else "None"; fi; mailq=$(exim -bpc);homedirslist=$(grep /home /var/log/exim_mainlog|grep cwd|cut -d\= -f2|awk '{print $1}'|sort|uniq -c|sort -n|tail -1|awk '{print $1}');if [ $mailq -ge 50 ]; then echo -e "Suspected Spamming...\n";exim -bp|exiwhat;grep /home /var/log/exim_mainlog|grep cwd|cut -d\= -f2|awk '{print $1}'|sort|uniq -c|sort -n|more; else echo -e "The count of mails on queue: $mailq \n `exim -bp | exiqsumm`"; fi; if [ $homedirslist -ge 50 ]; then echo -e "\n\nThe location of mails originating from php scripts:\n`grep /home /var/log/exim_mainlog|grep cwd|cut -d\= -f2|awk '{print $1}'|sort|uniq -c|sort -n|tail -5`"; else echo -e "exim summary \n `exim -bp|exiqsumm`"; fi
